window.RENFO_CONFIG = {
  MAPKIT_TOKEN: "eyJraWQiOiJGOVlQS1hBNFNEIiwidHlwIjoiSldUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJYS1E0MjRIUTMzIiwiaWF0IjoxNzcxNTE1MTY3LCJvcmlnaW4iOiIqLnJlbmZvLmFwcCJ9.z-ycIQdcxWkgTZLNpAlg9N0anT14BKlDy8Wydrv-dLJVBUji7ZS4b5N08NMmkElAFDkQC36QeepOHOFdHE_t7Q",
  ASSETS_BASE_URL: "https://assets.renfo.app"
};
